import type { Metadata } from 'next';
import { Inter, Manrope } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar';
import Footer from '@/components/footer';
import MainContextProvider from '@/context/main-context';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' >
      <MainContextProvider>
        <body className={`${manrope.className} relative overflow-x-hidden `}>
          <Navbar />

          {children}
          <Footer />
        </body>
      </MainContextProvider>
    </html>
  );
}
